# Change these first
owner: Cyberflix-Media
repo: Cyberflix-Status

# Add your sites here
sites:
  - name: Cyberflix Main Site
    url: https://www.cyberflix.io
  - name: Cyberflix Docs
    url: https://docs.cyberflix.io
    icon: https://archive.cyberflix.io/images/logos/SVGs/Docs.svg
  - name: Cyberflix Archive
    url: https://archive.cyberflix.io
    icon: https://archive.cyberflix.io/images/logos/SVGs/Archive.svg

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.cyberflix.io
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://archive.cyberflix.io/images/logos/SVGs/Status.svg
  favicon: https://archive.cyberflix.io/images/logos/SVGs/Status.svg
  name: Cyberflix - Status
  theme: dark
  introTitle: "<img src='https://archive.cyberflix.io/images/titles/Cyberflix-Status-Light.png' alt='' style='margin-left: auto;margin-right: auto;margin-top: 1em;display: block;width: 100%;'>"
  introMessage: The Cyberflix Project has been indefinetly suspended following the permanent suspension of Cyberflix Media's Google Account. Please visit cyfx.io for more information.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  css: ":root {--card-background-color: #161b22;--card-border-color: #161b22;--down-border-left-color: red;--up-border-left-color: limegreen;}body {background: url(https://archive.cyberflix.io/images/backgrounds/Main-Background.png); background-repeat: no-repeat; background-attachment: fixed; background-size: cover; -webkit-background-size: auto, cover; -moz-background-size: auto, cover; -o-background-size: auto, cover;} nav {display: none;} .icon.svelte-14gfn20.svelte-14gfn20.svelte-14gfn20 {height: 27px;}::-webkit-scrollbar {width: 5px;}::-webkit-scrollbar-track {background: #3B3B3B;}::-webkit-scrollbar-thumb {background: #888888; border-radius: 10px;}::-webkit-scrollbar-thumb:hover {background: #888888;}"
i18n:
  footer: Copyright © 2024 Cyberflix Media. All rights reserved.
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
