# Change these first
owner: BobDaGecko
repo: Cyberflix-Status

# Add your sites here
sites:
  - name: Cyberflix Frontend
    url: https://www.cyberflix.io
    icon: https://imgur.com/WETM3Qs.png
  - name: Cyberflix Backend
    url: https://backend.cyberflix.io
    icon: https://imgur.com/goTm1a2.png
  - name: Cyberflix Accounts
    url: https://accounts.cyberflix.io
    icon: https://imgur.com/WfykD6a.png
  - name: Cyberflix Speedtest
    url: https://speedtest.cyberflix.io
    icon: https://imgur.com/foLDaUS.png
  - name: Cyberflix Docs
    url: https://docs.cyberflix.io
    icon: https://imgur.com/i7W3fo6.png

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.cyberflix.io
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://imgur.com/cN1o7fQ.png
  favicon: https://imgur.com/cN1o7fQ.png
  name: Cyberflix - Status
  theme: dark
  introTitle: "<img src='https://imgur.com/aZOkMCR.png' alt='' style='margin-left: auto;margin-right: auto;margin-top: 1em;display: block;width: 100%;'>"
  introMessage: Welcome to the Cyberflix Status page. Here you will find the status for the entire media center.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  css: ":root {--card-background-color: #161b22;--card-border-color: #161b22;--down-border-left-color: red;--up-border-left-color: limegreen;}body {background: url(https://i.imgur.com/9vL4iNf.png); background-repeat: repeat, no-repeat; background-attachment: fixed, fixed; background-position: center center, center center; background-size: auto, cover; -webkit-background-size: auto, cover; -moz-background-size: auto, cover; -o-background-size: auto, cover;} nav {display: none;} .icon.svelte-14gfn20.svelte-14gfn20.svelte-14gfn20 {height: 27px;}::-webkit-scrollbar {width: 5px;}::-webkit-scrollbar-track {background: #3B3B3B;}::-webkit-scrollbar-thumb {background: #888888; border-radius: 10px;}::-webkit-scrollbar-thumb:hover {background: #888888;}"
i18n:
  footer: Copyright © 2021 Cyberflix Media. All rights reserved.
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
