# Change these first
owner: BobDaGecko
repo: Cyberflix-Status

# Add your sites here
sites:
  - name: Cyberflix Frontend
    url: https://www.cyberflix.io
    icon: https://imgur.com/DZswp1A.png
  - name: Cyberflix Backend
    url: https://backend.cyberflix.io
    icon: https://github.com/liaralabs/swizzin_dashboard/blob/master/static/img/favicon/android-chrome-512x512.png
  - name: Cyberflix Accounts
    url: https://accounts.cyberflix.io
    icon: https://imgur.com/iiWhMYv.png
  - name: Cyberflix Speedtest
    url: https://speedtest.cyberflix.io
    icon: https://imgur.com/fgPiJbP.png
  - name: Cyberflix Docs
    url: https://docs.cyberflix.io
    icon: https://imgur.com/m3TiLSb.png

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.cyberflix.io
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://imgur.com/vZfUIGH.png
  favicon: https://imgur.com/vZfUIGH.png
  name: Cyberflix Status
  theme: dark
  introTitle: "<img src='https://imgur.com/C6RHrNY.png' alt='' style='margin-left: auto;margin-right: auto;margin-top: 1em;display: block;width: 80%;'>"
  introMessage: Welcome to the Cyberflix Status page. Here you will find the status for the entire media center.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  css: "body {background: url(https://i.imgur.com/9vL4iNf.png);color: var(--body-text-color);} nav {display: none;} .icon.svelte-14gfn20.svelte-14gfn20.svelte-14gfn20 {height: 27px;} article {background: #161b22;border-color: #161b22;}"
  i18n:
    footer: © 2020 Cyberflix Media. All rights reserved.
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
