# Change these first
owner: Cyberflix Media
repo: Cyberflix-Status

# Add your sites here
sites:
  - name: Cyberflix Frontend
    url: https://www.cyberflix.io
    icon: https://archive.cyberflix.io/images/logos/SVGs/Logo.svg
  - name: Cyberflix Backend
    url: https://backend.cyberflix.io
    icon: https://archive.cyberflix.io/images/logos/SVGs/Backend.svg
  - name: Cyberflix Accounts
    url: https://accounts.cyberflix.io
    icon: https://archive.cyberflix.io/images/logos/SVGs/Accounts.svg
  - name: Cyberflix Speedtest
    url: https://speedtest.cyberflix.io
    icon: https://archive.cyberflix.io/images/logos/SVGs/Speedtest.svg
  - name: Cyberflix Docs
    url: https://docs.cyberflix.io
    icon: https://archive.cyberflix.io/images/logos/SVGs/Docs.svg
  - name: Cyberflix Archive
    url: https://archive.cyberflix.io
    icon: https://archive.cyberflix.io/images/logos/SVGs/Archive.svg

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.cyberflix.io
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://archive.cyberflix.io/images/logos/SVGs/Status.svg
  favicon: https://archive.cyberflix.io/images/logos/SVGs/Status.svg
  name: Cyberflix - Status
  theme: dark
  introTitle: "<img src='https://archive.cyberflix.io/images/titles/Cyberflix-Status-Light.png' alt='' style='margin-left: auto;margin-right: auto;margin-top: 1em;display: block;width: 100%;'>"
  introMessage: Welcome to the Cyberflix Status page. Here you will find the status for the entire media center.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
i18n:
  footer: Copyright © 2022 Cyberflix Media. All rights reserved.
