# Change these first
owner: BobDaGecko
repo: Cyberflix-Status

# Add your sites here
sites:
  - name: Cyberflix Frontend
    url: https://www.cyberflix.io
  - name: Cyberflix Backend
    url: https://backend.cyberflix.io
    icon: https://github.com/liaralabs/swizzin_dashboard/blob/master/static/img/favicon/favicon.ico
  - name: Cyberflix Accounts
    url: https://accounts.cyberflix.io
    icon: https://imgur.com/iiWhMYv.png
  - name: Cyberflix Speedtest
    url: https://speedtest.cyberflix.io
    icon: https://imgur.com/fgPiJbP.png
  - name: Cyberflix Docs
    url: https://docs.cyberflix.io
    icon: https://imgur.com/m3TiLSb.png

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.cyberflix.io
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://imgur.com/RDI71QW.png
  favicon: https://imgur.com/vZfUIGH.png
  name: Cyberflix Status
  theme: dark
  introTitle: "![](https://imgur.com/C6RHrNY.png)"
  introMessage: Welcome to the Cyberflix Status page. Here you will find the status for the entire media center.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
